### ISSUE TITLE
Make package public

### ISSUE THREAD

**Issue by johnbradley** [Imageomics/dataverse-access#8]
Currently the Docker container is private. Please change the dataverse-access package to allow public access.
https://github.com/Imageomics/dataverse-access/pkgs/container/dataverse-access

**Comment by johnbradley** [comment]
This problem can be seen from the command line using docker:
```
$ docker pull ghcr.io/imageomics/dataverse-access:0.0.1
Error response from daemon: Head "https://ghcr.io/v2/imageomics/dataverse-access/manifests/0.0.1": unauthorized
```

**Comment by hlapp** [comment]
The package is public now. This also revealed an organization-wide setting that allowed publishing only private packages, which I've changed now to also allow public and "internal" (to the organization) visibility.
